customhost = "database-1.c4z4hwprksdm.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "leeyingzheng-employee"
customregion = "us-east-1"
